[package]
name = "titlecase"
description = "A tool that capitlizes text according to a style defined by John Gruber for post titles on his website Daring Fireball."
version = "0.9.0"
authors = ["Wesley Moore <wes@wezm.net>"]

documentation = "https://docs.rs/crate/titlecase"
repository = "https://github.com/wezm/titlecase"

readme = "README.md"
license = "MIT"

keywords = ["title", "case", "capitalization", "capitilisation", "capitilize"]
categories = ["text-processing"]

[badges]
travis-ci = { repository = "https://github.com/wezm/titlecase" }
appveyor = { repository = "https://github.com/wezm/titlecase" }

[dependencies]
regex = "0.2.2"
